### ISSUE TITLE
I get this error when running logstash 7.1.0

### ISSUE THREAD

**Issue by kingram6865** [headius/backport9#2]
Trying to run logstash

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/home/kingram/logstash-7.1.0/logstash-core/lib/jars/jruby-complete-9.2.7.0.jar) to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Sending Logstash logs to /home/kingram/logstash-7.1.0/logs which is now configured via log4j2.properties
[2019-05-27T13:28:31,600][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (LoadError) load error: ffi/ffi -- java.lang.NullPointerException: null
============== Environment 
Raspbian 9 (Stretch)

$ echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-armhf

$ java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+1-Raspbian-1)
OpenJDK Server VM (build 11.0.3+1-Raspbian-1, mixed mode)

**Comment by dradetsky** [comment]
Fun fact: this occurs with almost every jruby operation on my computer. Originally, I thought it was just the version obtained via rvm, but it turns out to happen with my system jruby too (which makes sense since they're both the same maven pkg).

```
% jruby -v
jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 OpenJDK 64-Bit Server VM 12.0.1+12 on 12.0.1+12 +jit [linux-x86_64]
% jirb
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 :001 >
```

I should emphasize that this happens for damn near everything. Installing gems, running almost any program, etc.

also
```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode)
```

**Comment by yuyongbo** [comment]
it occured to me, too.

**Comment by brometeo** [comment]
We get this error running our application with Java 11. Is there something to worry about? Thanks.

**Comment by eistin** [comment]
It happens in my logstash container too. Is there any solution to fix this ?
My logstash is giving permission denied on every request, can it be linked to this warning ?

**Comment by chromis** [comment]
Hello,

Providing `--illegal-access=warn` to the `java` program invocation produces a _significant list_ of more illegal reflective accesses.

I managed to get rid of the warning mentioned in this issue: append `--add-opens java.base/java.io=ALL-UNNAMED` to the `java` program invocation. Another warning will simply pop up then. Hunting them all down in this particular way is surely possible.

That "fixes" the warnings, not the actual issue. I think the issue always has been there but that previous JDK's had no security mechanism - the Java Module System - in place that was able to detect this.

I therefore strongly suspect there's no real issue, yet. When a future OpenJDK defaults to denying such illegal access by default then things might get interesting ;)

**Do not do this in production** :: providing `--illegal-access=deny`, just to see what happens (With my JRuby experiments) gets rid of all warnings... but the reflection method calls will return `null` or throw something in this case? Anyway: my JRuby setup 'just seems to work' (and: I got an interesting _log_ message from JRuby suggesting adding `--add-opens java.base/sun.nio.ch=org.jruby.dist` for 'native subprocess control', indicating awareness about such issues in these projects).

I hope this helps to alleviate some of the worries. At least it alleviated mine ;)

**Comment by Kolano** [comment]
The update of JRuby in v7.4 seems to have significantly reduced these warnings. However one remains on...
com.headius.backport9.modules.Modules

**Comment by phonon112358** [comment]
I also get these warnings on Debian 10 (logstash 7.4.0, java 11.0.4).
Is there any solution available?

**Comment by Kolano** [comment]
> 
> 
> I also get these warnings on Debian 10 (logstash 7.4.0, java 11.0.4).
> Is there any solution available?

See the post directly above yours.

Here's my command to set up a current set of --add-opens parameters for the Logstash JVM, though the required list vacillates between versions...

```
sudo bash -c "echo -e '\n#Account for illegal reflective access warnings\n--add-opens=java.base/java.io=ALL-UNNAMED\n--add-opens=java.base/java.lang=ALL-UNNAMED\n--add-opens=java.base/java.lang.reflect=ALL-UNNAMED\n--add-opens=java.base/java.net=ALL-UNNAMED\n--add-opens=java.base/java.security=ALL-UNNAMED\n--add-opens=java.base/java.security.cert=ALL-UNNAMED\n--add-opens=java.base/java.util=ALL-UNNAMED\n--add-opens=java.base/java.util.concurrent=ALL-UNNAMED\n--add-opens=java.base/java.util.regex=ALL-UNNAMED\n--add-opens=java.base/java.util.zip=ALL-UNNAMED\n--add-opens=java.base/javax.crypto=ALL-UNNAMED\n--add-opens=java.management/sun.management=ALL-UNNAMED\n' >> /etc/logstash/jvm.options"
```

**Comment by phonon112358** [comment]
Thanks! This solved it for me...!

**Comment by phonon112358** [comment]
unfortunately, I am still getting those warnings...

**Comment by jsvd** [comment]
Current state with JRuby 9.2.9.0

```
❯ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10)
OpenJDK 64-Bit Server VM (build 11.0.5+10, mixed mode)

❯ jruby -v
jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 11.0.5+10 on 11.0.5+10 +jit [darwin-x86_64]

❯ JRUBY_OPTS="-J--illegal-access=warn" jruby  -e "puts 1" 
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method sun.nio.ch.NativeThread.signal(long)
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method sun.nio.ch.NativeThread.current()
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method java.lang.Object.finalize()
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method java.lang.Object.clone()
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field java.lang.reflect.Field.modifiers
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field javax.crypto.JceSecurity.isRestricted
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to field java.io.FileDescriptor.fd
1
```

**Comment by bitva77** [comment]
ditto with Logstash 7.5.1

**Comment by TheDevelolper** [comment]
yeah I'm getting these warnings. Will logstash still work?

**Comment by Kolano** [comment]
> yeah I'm getting these warnings. Will logstash still work?

It will, at least till Java is revised to prevent illegal reflective access. You can avoid these logged warnings by adding in appropriate --add-opens parameters to Logstash's jvm.options (refer Linux command line above).

**Comment by headius** [comment]
We continue to improve our integration with modules, so hopefully these will start going away as Logstash catches up JRuby. In many cases we simply will not do the offending reflective operation anymore. Unfortunately some these `add-opens` flags will always need to be there in order for us to maintain our high level of compatibility with CRuby.

**Comment by headius** [comment]
Regarding the warnings displayed for `puts 1`, this is not the case if you use the bash-based launcher that ships with JRuby:

```
$ JRUBY_OPTS="-J--illegal-access=warn" jruby  -e "puts 1"
1
```

However the jruby-launcher native executable has not been updated to have appropriate flags. See jruby/jruby-launcher#28 and jruby/jruby#5826.

**Comment by deivid-rodriguez** [comment]
@headius I'm still getting this warnings on a fresh install of `jruby-9.2.9.0` through rbenv on Linux. How do I know the exact values of `--add-opens` I have to put in `JAVA_OPTS` so that these go away?


```
$ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)

$  jruby -v
jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 11.0.5+10-post-Ubuntu-0ubuntu1.118.04 on 11.0.5+10-post-Ubuntu-0ubuntu1.118.04 +jit [linux-x86_64]

$ jruby -e "puts 1"
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Thank you :pray:.

**Comment by headius** [comment]
@deivid-rodriguez Yeah looks like this is because of the native launcher not being up to date still. We will try to get this fixed and released in the next week. At that point you should be able to `gem install jruby-launcher` for the updated logic that no longer warns (at least for this case).

**Comment by deivid-rodriguez** [comment]
Thanks @headius, that's really appreciated!

**Comment by headius** [comment]
Closing this because it's not a backport9 issue. JRuby is now adding proper `--add-opens` in its bash launcher and will soon do so in the native launcher too.

**Comment by headius** [comment]
The native launcher has been updated to honor the `.jruby.module_opts` file that the bash script uses, and to pass the appropriate `--add-opens` when that file is not present. Releases prior to 9.2.1 will not get any automatic `--add-opens` because they did not export a module name.
